flask:
  secret_key: demo
mongodb:
  db_name: app_db
  entities_collection: entities
  host: mongodb://localhost:27017/
web3:
  access_policy_contract_address: '0x8c5044Ce7fD70b827Ff7bEfdAAD8fCA357761E55'
  chain_id: 5
  host: https://goerli.infura.io/v3/3eeae409a6804076b6a67c5aeebd6c61
  institution_registry_contract_address: '0xaF17587dD0684909Cd0091B8Ff886E2FfAC7CE38'
  patient_registry_contract_address: '0xAc36ccfb3B5641383b2072c29bbD6C349Af5DFC3'
