flask:
  secret_key: demo
mongodb:
  db_name: app_db
  entities_collection: entities
  host: mongodb://localhost:27017/
web3:
  access_policy_contract_address: '0x5b1869D9A4C187F2EAa108f3062412ecf0526b24'
  chain_id: 1337
  host: http://127.0.0.1:8545
  institution_registry_contract_address: '0xCfEB869F69431e42cdB54A4F4f105C19C080A601'
  patient_registry_contract_address: '0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab'
