flask:
  secret_key: demo
mongodb:
  db_name: app_db
  entities_collection: entities
  host: mongodb://localhost:27017/
web3:
  access_policy_contract_address: '0xED389FA6475Bd5b50D3B97B0Cf20df2D3F8843bf'
  chain_id: 1337
  host: http://127.0.0.1:8545
  patient_registry_contract_address: '0xA341B26df1e3cfDAAe1c339aEB388bC9a87f007b'
