flask:
  secret_key: demo
mongodb:
  db_name: app_db
  entities_collection: entities
  host: mongodb://localhost:27017/
web3:
  access_policy_contract_address: '0x54b27c2adC7Cc8C2BB1a2F2CE3920E755d03ab2e'
  chain_id: 1337
  host: http://127.0.0.1:8545
  patient_registry_contract_address: '0x79A659df2011e2e8eCc8093DAd445B43B5361891'
