flask:
  secret_key: demo
mongodb:
  db_name: app_db
  entities_collection: entities
  host: mongodb://localhost:27017/
web3:
  access_policy_contract_address: '0x0CC224B9aaa136FddFD7E9bB277a1bdb6232620e'
  chain_id: 1337
  host: http://127.0.0.1:8545
  institution_registry_contract_address: '0x49C2c09A2cF792E1EBFFEDD7a1D7599e892da359'
  patient_registry_contract_address: '0xF5ddE8B60E194f70BA84c4D8af2CAD056c9D95e4'
