flask:
  secret_key: demo
mongodb:
  db_name: app_db
  entities_collection: entities
  host: mongodb://localhost:27017/
web3:
  access_policy_contract_address: '0x538d3062fAdFB17D40c26FaCAE6c55c076146803'
  chain_id: 1337
  host: http://127.0.0.1:8545
  patient_registry_contract_address: '0x916568cCcBD9967f0c0BA2a319b571F61a39FF8D'
